#!/usr/bin/env bash
# Install nginx on the web server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
