#!/usr/bin/env bash
# Configures redirect on nginx server
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
new='\trewrite ^/redirect_me https://youtu.be/PF5GBT9oJDo permanent;/n'
lineNo=47
FILE='/etc/nginx/sites-available/default'
sed -i "${lineNo}s~.*~${new}~" $FILE
sudo service nginx restart
