#!/usr/bin/env bash
# comment text

new_string="^/redirect_me https://youtu.be/PF5GBT9oJDo\npermanent;"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default
service nginx start
