#!/usr/bin/env bash
# Comment text
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo 'add_header X-Served-By $hostname' > /etc/nginx/nginx.conf
service nginx start
