#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom heade
original='server {'
replace='server {\n\tadd_header X-Served-By $hostname;'
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i "s~$original~$replace~g" /etc/nginx/sites-available/default
service nginx start
