#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom heade
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
lineNo=24
replace="\tadd_header X-Served-By $hostname;\n"
FILE='/etc/nginx/sites-available/default'
FILE2='/etc/nginx/sites-enabled/default'
sed -i "${lineNo}s~.*~${replace}~" $FILE
sed -i "${lineNo}s~.*~${replace}~" $FILE2
service nginx start
