#!/usr/bin/env bash
# Listening on port 80
file='/etc/nginx/sites-enabled/default'
text='\tlisten 80 default_server;\n\tlisten [::]:80 default_server;'
line=22
sed -i "${line}s~.*~${text}~" $file
service nginx restart
