#!/usr/bin/env bash
# text
count=0
while [ $count -ne 10 ]
do
	if [ $count = 3 ]
	then
		echo "bad luck"
	elif [ $count = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count=count+1 ))
done
