#!/usr/bin/env bash
# Run nginx as a user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /t
chmod 644 /etc/nginx/ngetc/nginx/sites-available/defaulinx.conf
sudo -u nginx service nginx start
